name: Elixir CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        elixir_version:
          - 1.11.4
          - 1.10.4
          - 1.9.4

    steps:
    - uses: actions/checkout@v2
    - name: Setup elixir
      uses: actions/setup-elixir@v1
      with:
        elixir-version: ${{ matrix.elixir_version }}
        otp-version: 22.2 # Define the OTP version [required]
        experimental-otp: true
    - name: Install Dependencies
      run: mix deps.get
    - name: Run Tests
      run: mix test
